[workflow]

[executables]
create_injections = /home/mrtodd/miniconda3/envs/ml_sbi/bin/pycbc_create_injections
simulate_data = /home/mrtodd/PEWSBI/bin/simulate_data
train_nn = /home/mrtodd/PEWSBI/bin/train_neural_network
sample = /home/mrtodd/PEWSBI/bin/sample
plot = /home/mrtodd/PEWSBI/bin/plot
pycbc_inference = /home/mrtodd/miniconda3/envs/ml_sbi/bin/pycbc_inference
plot_posterior = /home/mrtodd/miniconda3/envs/ml_sbi/bin/pycbc_inference_plot_posterior

# Options supplied here go to all uses of these executables in the workflow
[create_injections]
seed = 0

# Options for simulate_data
[simulate_data]
signal-length = 2048
delta-f = 512
epoch = 1126259459
monitor-rate = 500
DNRF = 5e20

# Options for training neural net
[train_nn]
DNRF = 5e20
IFO = H1
batch-size = 500
learning-rate = 1e-4
stop-after-epochs = 20

# Options for sampling
[sample]
IFOs = H1
channel-name = H1:sim-strain
DNRF = 5e20 
sample-rate = 512 
strain-high-pass = 5
fake-strain = aLIGOEarlyLowSensitivityP1200087
fake-strain-seed = 1234 
fake-strain-sample-rate = 2048 
fake-strain-flow =  10
gps-start-time = 1126259459
gps-end-time = 1126259463

[pycbc_inference]
seed = 0
processing-scheme = mkl
nprocesses = 2

# options to configure how Pegasus will run the workflow can be put here
[pegasus_profile]
pycbc|submit-directory = ./

# options that tell how much resources a particular job needs can be put here
# The exe key name is appended. If not specified, whatever the default
# resource request of your cluster is used.
[pegasus_profile-argument_exe]
# This example follows the condor format, any standard options from condor
# can be used.
condor|request_memory = 1000
condor|request_cpus = 2